// config.bin - 19:02:48 04/17/21, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class WeaponCabinet {
		units[] = {"WeaponCabinet"};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"DZ_Data", "DZ_Characters_Tops", "DZ_Characters_Backpacks", "DZ_Scripts", "DZ_Weapons_Firearms", "DZ_Characters_Pants", "DZ_Gear_Containers", "DZ_Characters_Shoes", "DZ_Gear_Consumables", "DZ_Weapons_Explosives", "DZ_Characters_Gloves"};
	};
};

class CfgVehicles {
	class Inventory_Base;	// External class reference
	class Container_Base;
    class FirstAidKit: Container_Base
	{
	InventorySlot="firstaid";
	};
	class AmmoBox: Container_Base
	{
		InventorySlot[]={"AmmoBox"};
	};
};

class CfgNonAIVehicles {
	class ProxyAttachment;	// External class reference
	
	class ProxyShoulder1 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder1";
		model = "WeaponCabinet\Proxy\shoulder1.p3d";
	};
	
	class ProxyShoulder2 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder2";
		model = "WeaponCabinet\Proxy\shoulder2.p3d";
	};
	
	class ProxyShoulder3 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder3";
		model = "WeaponCabinet\Proxy\shoulder3.p3d";
	};
	
	class ProxyShoulder4 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder4";
		model = "WeaponCabinet\Proxy\shoulder4.p3d";
	};
	
	class ProxyShoulder5 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder5";
		model = "WeaponCabinet\Proxy\shoulder5.p3d";
	};
	class ProxyShoulder6 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder6";
		model = "WeaponCabinet\Proxy\shoulder6.p3d";
	};
	
	class ProxyShoulder7 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder7";
		model = "WeaponCabinet\Proxy\shoulder7.p3d";
	};
	
	class ProxyShoulder8 : ProxyAttachment {
		scope = 2;
		inventorySlot = "shoulder8";
		model = "WeaponCabinet\Proxy\shoulder8.p3d";
	};
	
	class Proxy300rndbox : ProxyAttachment
    {
        scope = 2;
		inventorySlot="AmmoBox";
        model = "WeaponCabinet\Proxy\300rndbox.p3d";
    };
	class Proxy300rndbox1 : ProxyAttachment
    {
        scope = 2;
		inventorySlot="AmmoBox1";
        model = "WeaponCabinet\Proxy\300rndbox.p3d";
    };
	class Proxy300rndbox2 : ProxyAttachment
    {
        scope = 2;
		inventorySlot="AmmoBox2";
        model = "WeaponCabinet\Proxy\300rndbox.p3d";
    };
	class Proxy300rndbox3 : ProxyAttachment
    {
        scope = 2;
		inventorySlot="AmmoBox3";
        model = "WeaponCabinet\Proxy\300rndbox.p3d";
    };
	class Proxycanteen : ProxyAttachment
    {
        scope = 2;
		inventorySlot="Belt_Left";
        model = "WeaponCabinet\Proxy\canteen.p3d";
    };
	class Proxyfirstaid : ProxyAttachment
    {
        scope = 2;
		inventorySlot="firstAid";
        model = "WeaponCabinet\Proxy\firstaid.p3d";
    };
	class Proxyfirstaid1 : ProxyAttachment
    {
        scope = 2;
		inventorySlot="firstAid1";
        model = "WeaponCabinet\Proxy\firstaid1.p3d";
    };
	class Proxyfirstaid2 : ProxyAttachment
    {
        scope = 2;
		inventorySlot="firstAid2";
        model = "WeaponCabinet\Proxy\firstaid2.p3d";
    };
	class Proxyfirstaid3 : ProxyAttachment
    {
        scope = 2;
		inventorySlot="firstAid3";
        model = "WeaponCabinet\Proxy\firstaid3.p3d";
    };
};

class CfgSlots {
	class Slot_Shoulder1 {
		name = "Shoulder1";
		displayName = "Shoulder1";
		ghostIcon = "shoulderleft";
	};
	
	class Slot_Shoulder_2 {
		name = "Shoulder2";
		displayName = "Shoulder2";
		ghostIcon = "shoulderleft";
	};
	
	class Slot_Shoulder_3 {
		name = "Shoulder3";
		displayName = "Shoulder3";
		ghostIcon = "shoulderleft";
	};
	
	class Slot_Shoulder_4 {
		name = "Shoulder4";
		displayName = "Shoulder4";
		ghostIcon = "shoulderleft";
	};
	class Slot_Shoulder_5 {
		name = "Shoulder5";
		displayName = "Shoulder5";
		ghostIcon = "shoulderleft";
	};
		class Slot_Shoulder_6 {
		name = "Shoulder6";
		displayName = "Shoulder6";
		ghostIcon = "shoulderleft";
	};
	
	class Slot_Shoulder_7 {
		name = "Shoulder7";
		displayName = "Shoulder7";
		ghostIcon = "shoulderleft";
	};
	class Slot_Shoulder_8 {
		name = "Shoulder8";
		displayName = "Shoulder8";
		ghostIcon = "shoulderleft";
	};
	class Slot_FirstAid
    {
        name="FirstAid";
        displayName="FirstAid";
        ghostIcon="missing";
        selection="FirstAid";
    };
	class Slot_FirstAid1
    {
        name="FirstAid1";
        displayName="FirstAid1";
        ghostIcon="missing";
        selection="FirstAid1";
    };
	class Slot_FirstAid2
    {
        name="FirstAid2";
        displayName="FirstAid2";
        ghostIcon="missing";
        selection="FirstAid2";
    };
	class Slot_FirstAid3
    {
        name="FirstAid3";
        displayName="FirstAid3";
        ghostIcon="missing";
        selection="FirstAid3";
    };
	class Slot_AmmoBox
    {
        name="AmmoBox";
        displayName="AmmoBox";
        ghostIcon="magazine";
        selection="AmmoBox";
    };
	class Slot_AmmoBox1
    {
        name="AmmoBox1";
        displayName="AmmoBox1";
        ghostIcon="magazine";
        selection="AmmoBox1";
    };
	class Slot_AmmoBox2
    {
        name="AmmoBox2";
        displayName="AmmoBox2";
        ghostIcon="magazine";
        selection="AmmoBox2";
    };
	class Slot_AmmoBox3
    {
        name="AmmoBox3";
        displayName="AmmoBox3";
        ghostIcon="magazine";
        selection="AmmoBox3";
    };
	class Slot_Belt_Left
    {
        name="Belt_Left";
        displayName="Belt_Left";
        ghostIcon="Canteen";
        selection="Canteen";
    };	
};

class cfgWeapons {
	class RifleCore;	// External class reference
	
	class Rifle_Base : RifleCore {
		inventorySlot[] = {"Shoulder", "Melee", "Shoulder1", "Shoulder2", "Shoulder3", "Shoulder4", "Shoulder5", "Shoulder6", "Shoulder7", "Shoulder8", "Shoulder9", "Shoulder10", "Shoulder11", "Shoulder12", "Shoulder13", "Shoulder14", "Shoulder15", "Shoulder16", "Shoulder17", "Shoulder18", "Shoulder19", "Shoulder20", "Shoulder21", "Shoulder22", "Shoulder23", "Shoulder24", "Shoulder25", "Shoulder26", "Shoulder27", "Shoulder28", "Shoulder29", "Shoulder30"};
	};
};
